name: CI (Python)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (lint)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install lint and format deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black isort
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
      - name: Check code formatting with Black
        shell: bash
        run: |
          python -m black --check --diff --color src tests
          echo "✅ Code formatting is perfect!"
      - name: Check import sorting with isort
        shell: bash
        run: |
          python -m isort --check-only --diff src tests
          echo "✅ Import sorting is perfect!"
      - name: Lint with flake8
        shell: bash
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    needs: lint
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-latest
            python-version: "3.14"
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || false }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install test deps
        shell: bash
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest pytest-cov black isort
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e .
      - name: Run tests with coverage
        shell: bash
        run: |
          python -m pytest -q --junitxml=pytest-junit.xml --cov=src/vaultlint --cov-fail-under=100 --cov-report=term-missing
          echo "✅ 100% CODE COVERAGE ACHIEVED!"
      - name: Publish test report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: pytest-junit.xml
          check_name: Test Report
          detailed_summary: true
          include_passed: true
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            pytest-junit.xml
            .pytest_cache
          if-no-files-found: ignore
